shell: shell.c sys/memo.c sys/libloader.c sys/recursive2.c sys/perror.c sys/time.c sys/mem_list.c
	gcc -Wall shell.c sys/memo.c sys/libloader.c sys/recursive2.c sys/perror.c sys/banner.c sys/time.c sys/mem_list.c -o shell -ldl -lssl -lcrypto -lrt
